version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: alumni-portal-server
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
